# Simple localization handler
# For Android/Flet, we can use simple dict mapping or gettext
# For simplicity and speed, we use a dict-based approach.

TRANSLATIONS = {
    "en": {
        "home": "Home",
        "library": "Library",
        "search": "Search",
        "settings": "Settings",
        "play": "Play",
        "pause": "Pause",
        "stop": "Stop",
        "download": "Download",
        "history": "Watch History",
        "favorites": "Favorites",
        "collections": "Collections",
        "downloads": "Downloads",
        "paste_link": "Paste Link from Clipboard",
        "search_youtube": "Search YouTube",
        "recent_activity": "Recent Activity",
        "no_results": "No results found.",
        "searching": "Searching...",
        "loading": "Loading...",
        "add_favorite": "Add to Favorites",
        "add_collection": "Add to Collection",
        "copy_link": "Copy Link",
        "video": "Video",
        "audio": "Audio",
        "cancel": "Cancel",
        "close": "Close",
        "create": "Create",
        "new_collection": "New Collection",
        "collection_name": "Collection Name",
        "select_collection": "Select Collection",
        "download_started": "Download started...",
        "download_completed": "Download Completed",
        "download_failed": "Download Failed: {}",
        "link_copied": "Link copied to clipboard",
        "open_browser": "Open in Browser",
        "dark_mode": "Dark Mode",
        "language": "Language",
        "skip_silence": "Skip Silence",
        "auto_play_next": "Auto Play Next",
        "repeat_track": "Repeat Track",
        "confirm": "Confirm",
        "delete_confirm": "Are you sure you want to delete this?",
        "clear_history": "Clear History",
        "clear_favorites": "Clear Favorites",
    },
    "vi": {
        "home": "Trang chủ",
        "library": "Thư viện",
        "search": "Tìm kiếm",
        "settings": "Cài đặt",
        "play": "Phát",
        "pause": "Tạm dừng",
        "stop": "Dừng",
        "download": "Tải xuống",
        "history": "Lịch sử xem",
        "favorites": "Yêu thích",
        "collections": "Bộ sưu tập",
        "downloads": "Đã tải xuống",
        "paste_link": "Dán liên kết từ bộ nhớ tạm",
        "search_youtube": "Tìm kiếm YouTube",
        "recent_activity": "Hoạt động gần đây",
        "no_results": "Không tìm thấy kết quả.",
        "searching": "Đang tìm kiếm...",
        "loading": "Đang tải...",
        "add_favorite": "Thêm vào yêu thích",
        "add_collection": "Thêm vào bộ sưu tập",
        "copy_link": "Sao chép liên kết",
        "video": "Video",
        "audio": "Âm thanh",
        "cancel": "Hủy",
        "close": "Đóng",
        "create": "Tạo",
        "new_collection": "Bộ sưu tập mới",
        "collection_name": "Tên bộ sưu tập",
        "select_collection": "Chọn bộ sưu tập",
        "download_started": "Đã bắt đầu tải xuống...",
        "download_completed": "Tải xuống hoàn tất",
        "download_failed": "Tải xuống thất bại: {}",
        "link_copied": "Đã sao chép liên kết vào bộ nhớ tạm",
        "open_browser": "Mở trong trình duyệt",
        "dark_mode": "Chế độ tối",
        "language": "Ngôn ngữ",
        "skip_silence": "Bỏ qua khoảng lặng",
        "auto_play_next": "Tự động phát tiếp",
        "repeat_track": "Lặp lại bài",
        "confirm": "Xác nhận",
        "delete_confirm": "Bạn có chắc chắn muốn xóa không?",
        "clear_history": "Xóa lịch sử",
        "clear_favorites": "Xóa yêu thích",
    }
}

from .settings import config_get

def _(key):
    lang = config_get("lang") or "en"
    if lang not in TRANSLATIONS:
        lang = "en"
    return TRANSLATIONS[lang].get(key, key) # Return key if not found (fallback)
